### ISSUE TITLE
Blurry content

### ISSUE THREAD

**Issue by tudoroancea** [ionyshch/cmake-qt5widgets-macos#5]
Hello there ! 
I tried to build your project using CMake 3.17.3 and Qt 5.14 (I have not modified any of your source files) but for some reason the window content and the window itself is kinda blurry. Even the top screen menu bar is blurry. 
I never had such problems with other projects. Any idea what caused it ?
Thanks in advance.

**Comment by ionyshch** [comment]
Hi!

I've just checked with CMake version 3.19.3 and Qt 5.15.2 on macOS 10.15.7.

I had to use cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt
where the path is the one reported by `brew info qt5`

Don't see anything blurry.

If the problem persists, could you, please, post a screenshot here.
